language: rust
cache: cargo
env:
  - TRAVIS=1
matrix:
  include:
    - rust: stable
      before_script:
        - rustup component add rustfmt
        - rustup component add clippy
      script: ./run_tests
