language: rust
cache: cargo
matrix:
  include:
    - rust: stable
      before_script:
        - rustup component add rustfmt-preview
      script:
        - ./stable-tests

    - rust: nightly
      before_script:
        - rustup component add clippy-preview
      script:
        - ./nightly-tests
