#!/bin/sh

set -e

echo "\033[36;1mRunning tests on debug with default features:\033[0m"
cargo test

echo "\033[36;1mRunning tests on release with default features:\033[0m"
cargo test --release

echo "\033[36;1mRunning tests on debug with force-static:\033[0m"
cargo test --features force-static

echo "\033[36;1mRunning tests on release with force-dynamic:\033[0m"
cargo test --release --features force-dynamic

echo "\033[36;1mRunning rustfmt:\033[0m"
cargo fmt -- --write-mode=check

echo "\033[36;1mRunning clippy:\033[0m"
cargo +nightly clippy --all-features -- -D clippy
