#!/bin/bash

set -e

echo -e "\033[36;1mRunning clippy:\033[0m"
cargo +nightly clippy -- -D clippy && \
    (cd static-feature-tests && cargo +nightly clippy -- -D clippy) && \
    (cd dynamic-feature-tests && cargo +nightly clippy -- -D clippy)
